// window.App: 全局命名空间（零安装原型用）
window.App = window.App || {};

App.Const = {
  bottomTabs: [
    { key: "home", label: "首页", sub: "看收入/做任务" },
    { key: "tasks", label: "学习任务", sub: "按阶段/按目标" },
    { key: "growth", label: "我的成长", sub: "奖励/勋章" },
  ],
  statuses: {
    not_started: "未开始",
    in_progress: "进行中",
    completed: "已完成",
    passed: "已通过",
    booked: "已预约",
    substituted: "已替代完成",
  },
  priorityLabels: {
    must: "必做",
    strong: "强烈建议",
    recommended: "推荐",
  },
  contentTypes: {
    certificate: "证书",
    mock: "Mock",
    workshop: "Workshop",
    dinoU: "Dino U",
  },
  goals: [
    { key: "qualify_fast", name: "更快拿到授课资格" },
    { key: "trial_performance", name: "提升试课表现" },
    { key: "booking_opportunity", name: "提高订课机会" },
    { key: "stability", name: "提升课堂稳定性" },
    { key: "avoid_issues", name: "避免常见问题影响收入" },
  ],
  stages: [
    {
      key: "M0",
      month: "Month0",
      title: "入职启动 + 基础打底",
      goal: "先把规则与基础能力补齐，保证能稳定开课。",
      theme: "starter",
    },
    { key: "M1", month: "Month1", title: "能力提升", goal: "提升试课表现与订课机会，拓展证书覆盖。", theme: "boost" },
    { key: "M2", month: "Month2", title: "增长加速", goal: "冲刺更高课量与更高价值证书，放大增长。", theme: "accelerate" },
    { key: "M3", month: "Month3", title: "Rising Star 新秀养成", goal: "做高影响力任务，稳定表现，冲刺 Rising Star。", theme: "rising" },
  ],
};

App.FakeDB = {
  // 内容库：所有详情页都复用（ContentDetail）
  contents: [
    // 证书（必备）
    {
      id: "cert-core-2-3",
      type: "certificate",
      name: "主修 2-3 级别证书",
      short: "大量订课必备基础证书，覆盖核心主修等级。",
      points: 18,
      tags: ["大量订课必备证书"],
      suitableStages: ["M0", "M1", "M2", "M3"],
      benefit: "更快解锁稳定订课机会，提升可排课覆盖。",
      replaces: [],
      repeats: [],
      next: ["mock-trial-2-3", "workshop-kickoff"],
    },
    {
      id: "cert-trial-2-3",
      type: "certificate",
      name: "试听证书 Lv2-3",
      short: "提升试听课表现与转化机会的关键证书。",
      points: 16,
      tags: ["大量订课必备证书", "当前热门推荐"],
      suitableStages: ["M0", "M1", "M2"],
      benefit: "提升试听转化与高价值课机会。",
      replaces: [],
      repeats: [],
      next: ["mock-trial-2-3-advanced", "cert-core-4-6"],
    },
    {
      id: "cert-core-4-6",
      type: "certificate",
      name: "主修 4-6 级别证书",
      short: "拓展主修覆盖到更高等级，增加订课选择。",
      points: 22,
      tags: ["大量订课必备证书", "当前热门推荐"],
      suitableStages: ["M1", "M2", "M3"],
      benefit: "增加可授课范围，提升订课机会。",
      replaces: [],
      repeats: [],
      next: ["mock-literature-5-8", "cert-core-7-8"],
    },

    // Mock（基础/进阶）
    {
      id: "mock-trial-2-3",
      type: "mock",
      name: "基础 Mock：主修试听 Lv2-3",
      short: "起步包必做：把试听课关键环节跑通。",
      points: 14,
      tags: ["起步包"],
      suitableStages: ["M0", "M1"],
      benefit: "提高试听表现，减少早期常见失误。",
      replaces: [],
      repeats: [],
      next: ["dino-portal-intro", "dino-cancellation-video"],
    },
    {
      id: "mock-trial-1",
      type: "mock",
      name: "基础 Mock：主修试听 Lv1",
      short: "补齐低阶试听基础节奏与互动。",
      points: 10,
      tags: [],
      suitableStages: ["M0", "M1"],
      benefit: "更稳的课堂节奏与互动引导。",
      replaces: [],
      repeats: [],
      next: ["mock-trial-2-3"],
    },
    {
      id: "mock-trial-4-6",
      type: "mock",
      name: "基础 Mock：主修试听 Lv4-6",
      short: "为更高等级试听做准备。",
      points: 12,
      tags: [],
      suitableStages: ["M1", "M2"],
      benefit: "提升高阶试听课掌控感。",
      replaces: [],
      repeats: [],
      next: ["cert-core-4-6"],
    },
    {
      id: "mock-graded-reading-4-6",
      type: "mock",
      name: "进阶 Mock：分级阅读 4-6",
      short: "进阶任务：成长积分更高。",
      points: 24,
      tags: ["高成长积分"],
      suitableStages: ["M2", "M3"],
      benefit: "提升高阶内容讲解与互动深度。",
      replaces: [],
      repeats: [],
      next: ["cert-core-4-6"],
    },
    {
      id: "mock-literature-5-8",
      type: "mock",
      name: "进阶 Mock：Literature Reading Lv5-8",
      short: "进阶任务：适合冲刺阶段排名与奖励。",
      points: 28,
      tags: ["高成长积分"],
      suitableStages: ["M2", "M3"],
      benefit: "提升高价值课表现与订课机会。",
      replaces: [],
      repeats: [],
      next: ["cert-core-7-8"],
    },
    {
      id: "cert-core-7-8",
      type: "mock",
      name: "进阶 Mock：主修证书 Lv7-8（挑战）",
      short: "高难度高回报：适合 Month3 冲刺。",
      points: 30,
      tags: ["高成长积分"],
      suitableStages: ["M3"],
      benefit: "冲刺更高价值机会与成长标签。",
      replaces: [],
      repeats: [],
      next: [],
    },

    // Workshops
    {
      id: "workshop-kickoff",
      type: "workshop",
      name: "New Teacher Kick Off",
      short: "规则学习模块方式一：参加 Kick Off 即视为完成。",
      points: 12,
      tags: ["基础规则主题", "起步包"],
      suitableStages: ["M0", "M1"],
      benefit: "更快理解平台规则，减少影响收入的常见问题。",
      replaces: ["dino-portal-intro", "dino-cancellation-video"],
      repeats: [],
      next: ["cert-trial-2-3"],
    },

    // Dino U
    {
      id: "dino-portal-intro",
      type: "dinoU",
      name: "Teacher Portal Introduction",
      short: "规则学习模块方式二之一：未参加 Kick Off 可完成此项。",
      points: 6,
      tags: ["基础规则学习", "起步包"],
      suitableStages: ["M0", "M1"],
      benefit: "掌握老师端工具与流程，减少操作失误。",
      replaces: [],
      repeats: ["workshop-kickoff"],
      next: ["dino-cancellation-video"],
    },
    {
      id: "dino-cancellation-video",
      type: "dinoU",
      name: "Teaching Tip Video: Understanding Class Cancellations",
      short: "规则学习模块方式二之二：与 Portal Introduction 共同完成。",
      points: 8,
      tags: ["基础规则学习", "起步包"],
      suitableStages: ["M0", "M1"],
      benefit: "减少取消/缺勤等风险，保护收入与机会。",
      replaces: [],
      repeats: ["workshop-kickoff"],
      next: ["cert-trial-2-3"],
    },

    // 额外内容（用于按目标找）
    {
      id: "dino-income-risk",
      type: "dinoU",
      name: "常见问题清单：迟到/投诉/缺勤如何影响收入",
      short: "帮助你避坑，减少扣减并保护订课机会。",
      points: 10,
      tags: ["热门"],
      suitableStages: ["M0", "M1", "M2", "M3"],
      benefit: "降低风险事件发生率，稳定收入与机会。",
      replaces: [],
      repeats: [],
      next: ["workshop-kickoff"],
    },
  ],

  // 任务定义：主线“看收入→做任务→看成长”
  // 说明：任务可以映射到一个内容（contentId）或一组内容（starter module）
  tasks: [
    {
      id: "task-rule-pack",
      name: "规则学习模块（Kick Off 或 Dino U 两项）",
      priority: "must",
      type: "dinoU",
      reason: "起步包必做：减少影响收入与机会的常见问题。",
      benefit: "减少取消/缺勤/投诉风险，稳定订课。",
      points: 12,
      stageKeys: ["M0", "M1"],
      goalKeys: ["avoid_issues", "stability"],
      contentGroup: ["workshop-kickoff", "dino-portal-intro", "dino-cancellation-video"],
      completionRule: "ANY_OF", // 完成 workshop-kickoff 或 (portal + cancellation)
    },
    {
      id: "task-cert-core-2-3",
      name: "主修 2-3 级别证书",
      priority: "must",
      type: "certificate",
      reason: "大量订课必备：先把核心等级证书拿到。",
      benefit: "更快解锁稳定订课机会。",
      points: 18,
      stageKeys: ["M0", "M1", "M2", "M3"],
      goalKeys: ["qualify_fast", "booking_opportunity"],
      contentId: "cert-core-2-3",
    },
    {
      id: "task-mock-trial-2-3",
      name: "基础 Mock：主修试听 Lv2-3",
      priority: "strong",
      type: "mock",
      reason: "起步包核心任务：试听表现越稳，越容易获得机会。",
      benefit: "提升试听课表现与课堂节奏。",
      points: 14,
      stageKeys: ["M0", "M1"],
      goalKeys: ["trial_performance", "qualify_fast"],
      contentId: "mock-trial-2-3",
    },
    {
      id: "task-cert-trial-2-3",
      name: "试听证书 Lv2-3",
      priority: "strong",
      type: "certificate",
      reason: "近期热门推荐：转化更好、机会更多。",
      benefit: "提升试听转化与高价值课机会。",
      points: 16,
      stageKeys: ["M0", "M1", "M2"],
      goalKeys: ["trial_performance", "booking_opportunity"],
      contentId: "cert-trial-2-3",
    },
    {
      id: "task-cert-core-4-6",
      name: "主修 4-6 级别证书",
      priority: "recommended",
      type: "certificate",
      reason: "扩大覆盖：更高等级=更多订课选择。",
      benefit: "增加可授课范围，提升订课机会。",
      points: 22,
      stageKeys: ["M1", "M2", "M3"],
      goalKeys: ["booking_opportunity"],
      contentId: "cert-core-4-6",
    },
    {
      id: "task-dino-income-risk",
      name: "常见问题清单：迟到/投诉/缺勤如何影响收入",
      priority: "recommended",
      type: "dinoU",
      reason: "避免扣减：保护收入与后续机会。",
      benefit: "降低风险事件，稳定收入。",
      points: 10,
      stageKeys: ["M0", "M1", "M2", "M3"],
      goalKeys: ["avoid_issues"],
      contentId: "dino-income-risk",
    },
    {
      id: "task-mock-literature-5-8",
      name: "进阶 Mock：Literature Reading Lv5-8",
      priority: "recommended",
      type: "mock",
      reason: "高成长积分：更接近前30%奖励更快。",
      benefit: "冲刺成长积分与高价值机会。",
      points: 28,
      stageKeys: ["M2", "M3"],
      goalKeys: ["booking_opportunity", "trial_performance"],
      contentId: "mock-literature-5-8",
    },
  ],

  // Tier 激励：示意用（可迭代为真实规则）
  tierRules: {
    Tier1: [{ upTo: 40, perClass: 0.0 }, { upTo: 80, perClass: 0.5 }, { upTo: Infinity, perClass: 1.0 }],
    Tier2: [{ upTo: 40, perClass: 0.2 }, { upTo: 80, perClass: 0.8 }, { upTo: Infinity, perClass: 1.2 }],
    Tier3: [{ upTo: 40, perClass: 0.5 }, { upTo: 80, perClass: 1.0 }, { upTo: Infinity, perClass: 1.5 }],
  },
};
